-- Smart Inbox Assistant - Oracle Schema
-- Phase 0: Core tables for ingestion, classification, extraction, and audit

-- Incoming messages (emails)
CREATE TABLE INCOMING_MESSAGE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender VARCHAR2(500),
    subject VARCHAR2(1000),
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    body_text CLOB,
    raw_source_ref VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Attachments (PDFs and other files)
CREATE TABLE ATTACHMENT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES INCOMING_MESSAGE(id),
    filename VARCHAR2(500),
    mime_type VARCHAR2(200),
    pdf_type VARCHAR2(100), -- 'digital', 'scanned', 'article', 'non_english'
    storage_ref VARCHAR2(500),
    page_count NUMBER,
    language_detected VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Model runs (traceability for AI decisions)
CREATE TABLE MODEL_RUN (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR2(200),
    prompt_version VARCHAR2(100),
    input_ref VARCHAR2(500),
    output_ref VARCHAR2(500),
    latency_ms NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Classification results (multi-label)
CREATE TABLE CLASSIFICATION_RESULT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES INCOMING_MESSAGE(id),
    category VARCHAR2(100), -- 'ICSR', 'PQC', 'MI', 'NOT_RELEVANT'
    confidence_tier VARCHAR2(20), -- 'HIGH', 'MEDIUM', 'LOW'
    reason VARCHAR2(1000),
    model_run_id NUMBER REFERENCES MODEL_RUN(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Extracted fields with provenance
CREATE TABLE EXTRACTED_FIELD (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_result_id NUMBER REFERENCES CLASSIFICATION_RESULT(id),
    field_group VARCHAR2(100), -- 'Patient', 'Reporter', 'Product', 'Reaction', 'Severity', 'Narrative', 'PQC', 'MI'
    field_name VARCHAR2(200),
    field_value CLOB,
    confidence_tier VARCHAR2(20), -- 'HIGH', 'MEDIUM', 'LOW'
    source_type VARCHAR2(50), -- 'email_body', 'pdf_page', 'attachment'
    source_ref VARCHAR2(500), -- page #, char offset, table cell reference
    verified_flag NUMBER(1) DEFAULT 0,
    extraction_run_id NUMBER REFERENCES MODEL_RUN(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Reviewer actions (append-only audit trail)
CREATE TABLE REVIEWER_ACTION (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_result_id NUMBER REFERENCES CLASSIFICATION_RESULT(id),
    reviewer_id VARCHAR2(100),
    action_type VARCHAR2(50), -- 'accept', 'override'
    previous_value CLOB,
    new_value CLOB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit log (system-wide traceability)
CREATE TABLE AUDIT_LOG (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR2(100),
    entity_id NUMBER,
    event_type VARCHAR2(100),
    actor VARCHAR2(100),
    payload_ref VARCHAR2(500),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IDX_INCOMING_MESSAGE_RECEIVED ON INCOMING_MESSAGE(received_at);
CREATE INDEX IDX_ATTACHMENT_MESSAGE ON ATTACHMENT(message_id);
CREATE INDEX IDX_CLASSIFICATION_MESSAGE ON CLASSIFICATION_RESULT(message_id);
CREATE INDEX IDX_EXTRACTED_FIELD_RESULT ON EXTRACTED_FIELD(classification_result_id);
CREATE INDEX IDX_AUDIT_LOG_ENTITY ON AUDIT_LOG(entity_type, entity_id);

-- Sample data for testing
INSERT INTO INCOMING_MESSAGE (sender, subject, body_text, raw_source_ref) 
VALUES ('test@example.com', 'Test Safety Report', 'Patient experienced headache after taking Drug X.', 'test_email_001');

COMMIT;
