-- Smart Inbox Assistant - Oracle Database Schema
-- Phase 0: Core tables for audit trail and traceability

-- Model Run tracking (every AI decision traceable)
CREATE TABLE MODEL_RUN (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR2(255) NOT NULL,
    prompt_version VARCHAR2(50),
    input_ref CLOB,
    output_ref CLOB,
    latency_ms NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Incoming messages from mailbox
CREATE TABLE INCOMING_MESSAGE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender VARCHAR2(500) NOT NULL,
    subject VARCHAR2(1000),
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    body_text CLOB,
    raw_source_ref VARCHAR2(500),
    processed_flag NUMBER(1) DEFAULT 0
);

-- Attachments (PDFs and other files)
CREATE TABLE ATTACHMENT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES INCOMING_MESSAGE(id),
    filename VARCHAR2(500) NOT NULL,
    mime_type VARCHAR2(100),
    pdf_type VARCHAR2(50), -- 'digital', 'scanned', 'article', 'non_english'
    storage_ref VARCHAR2(500),
    page_count NUMBER,
    language_detected VARCHAR2(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Classification results (multi-label support)
CREATE TABLE CLASSIFICATION_RESULT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES INCOMING_MESSAGE(id),
    category VARCHAR2(50) NOT NULL, -- 'ICSR', 'PQC', 'MI', 'NOT_RELEVANT'
    confidence_tier VARCHAR2(20), -- 'HIGH', 'MEDIUM', 'LOW'
    reason VARCHAR2(1000),
    model_run_id NUMBER REFERENCES MODEL_RUN(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Extracted fields with provenance/traceability
CREATE TABLE EXTRACTED_FIELD (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_result_id NUMBER REFERENCES CLASSIFICATION_RESULT(id),
    field_group VARCHAR2(50) NOT NULL, -- 'Patient', 'Reporter', 'Product', 'Reaction', 'Severity', 'Narrative', 'PQC', 'MI'
    field_name VARCHAR2(200) NOT NULL,
    field_value CLOB,
    confidence_tier VARCHAR2(20), -- 'HIGH', 'MEDIUM', 'LOW'
    source_type VARCHAR2(50), -- 'email_body', 'pdf_page'
    source_ref VARCHAR2(500), -- page number, char offset, table cell reference
    verified_flag NUMBER(1) DEFAULT 0,
    extraction_run_id NUMBER REFERENCES MODEL_RUN(id)
);

-- Reviewer actions (append-only audit log)
CREATE TABLE REVIEWER_ACTION (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_result_id NUMBER REFERENCES CLASSIFICATION_RESULT(id),
    reviewer_id VARCHAR2(100) NOT NULL,
    action_type VARCHAR2(50) NOT NULL, -- 'accept', 'override'
    previous_value CLOB,
    new_value CLOB,
    field_name VARCHAR2(200),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comprehensive audit log
CREATE TABLE AUDIT_LOG (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR2(100) NOT NULL,
    entity_id NUMBER NOT NULL,
    event_type VARCHAR2(100) NOT NULL,
    actor VARCHAR2(100),
    payload_ref CLOB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Processing jobs queue
CREATE TABLE PROCESSING_JOB (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES INCOMING_MESSAGE(id),
    status VARCHAR2(50) DEFAULT 'PENDING', -- 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'
    error_message VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IDX_INCOMING_MESSAGE_RECEIVED ON INCOMING_MESSAGE(received_at);
CREATE INDEX IDX_ATTACHMENT_MESSAGE ON ATTACHMENT(message_id);
CREATE INDEX IDX_CLASSIFICATION_MESSAGE ON CLASSIFICATION_RESULT(message_id);
CREATE INDEX IDX_EXTRACTED_FIELD_RESULT ON EXTRACTED_FIELD(classification_result_id);
CREATE INDEX IDX_PROCESSING_JOB_STATUS ON PROCESSING_JOB(status);

-- Sequences (if needed for compatibility)
-- Oracle 12c+ supports IDENTITY columns, but sequences provided for older versions
CREATE SEQUENCE SEQ_MODEL_RUN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INCOMING_MESSAGE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTACHMENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLASSIFICATION_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXTRACTED_FIELD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEWER_ACTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUDIT_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROCESSING_JOB START WITH 1 INCREMENT BY 1;
